set background=dark
set number
set relativenumber
set cursorline
set expandtab
set tabstop=4
set shiftwidth=4
set hlsearch
set incsearch
set ignorecase
set smartcase
set termguicolors
syntax on

" Use built-in habamax (clean dark theme close to VS Code dark)
colorscheme habamax

" Diff colors (cleaner than defaults)
highlight DiffAdd    guibg=#1a3a1a guifg=NONE
highlight DiffDelete guibg=#3a1a1a guifg=#555555
highlight DiffChange guibg=#1a2a3a guifg=NONE
highlight DiffText   guibg=#2a4a6a guifg=NONE

" Git shortcuts
command! Gd Gdiffsplit | wincmd l
cnoreabbrev gd Gd
cnoreabbrev diff Gd

