#!/bin/bash
# Random wallpaper rotation for Sway - different wallpaper per monitor

WALLPAPER_DIR="$HOME/Pictures/wallpapers"

# Get all wallpapers and shuffle
WALLPAPERS=($(find "$WALLPAPER_DIR" -maxdepth 1 -type f \( -name "*.jpg" -o -name "*.png" -o -name "*.webp" \) | shuf))

# Get all outputs
OUTPUTS=($(swaymsg -t get_outputs | jq -r '.[].name'))

# Set different wallpaper for each output
for i in "${!OUTPUTS[@]}"; do
    # Cycle through wallpapers if more monitors than images
    idx=$((i % ${#WALLPAPERS[@]}))
    swaymsg "output ${OUTPUTS[$i]} bg '${WALLPAPERS[$idx]}' fill"
done
